### ISSUE TITLE
a Few recommendations

### ISSUE THREAD

**Issue by mehargags** [abbat/pclcmd#1]
I Anton,
thanks for starting this project on request.

Just a small point, when you rsync or put file into pcloud, can you return the file size in mb/gb that was put ?

The reason for this is, I put files from CRON, it just tells me:

**_Transfer: /home/backup/admin.2016-03-15.tar -> disk:/HLL-IA2000/backup/admin.2016-03-15.tar
Delete: disk:/backup/admin.2016-02-24.tar_**

It'd be really helpful if it can say "Transfer: /home/backup/admin.2016-03-15.tar **_(1.5GB)_**" concatenated in the echo statement. This will show the byte size moved.

Thanks

**Comment by abbat** [comment]
v0.1
