### ISSUE TITLE
remote upload

### ISSUE THREAD

**Issue by rxng** [abbat/pclcmd#6]
Just wondering if there will be remote upload support?
e.g. download to pcloud from a url

**Comment by abbat** [comment]
I can not find remote download API in [documentation](https://docs.pcloud.com/). So, answer is "no".

**Comment by rxng** [comment]
Yes, there is

https://docs.pcloud.com/methods/file/downloadfile.html

And I wrote a function for the script:

def pcl_remotedl_cmd(options, args):

    source = args[0]
    target = args[1] if len(args)>1 else '/Remote'

    if not args[0]:
        raise pclError(1, "Source not specified")
    if '://' not in args[0]:
        raise pclError(1, "Not valid url")

    args = {
        "url"      : source,
        "nopartial" : 1,
        "path"  : target
    }

    method = "GET"
    url    = options.baseurl + "/downloadfile"

    headers = pcl_headers(options.token)

    output = pcl_query_retry(options, method, url, args, headers, source)
    print(output)

**Comment by abbat** [comment]
Oh! Would you make PR?

**Comment by rxng** [comment]
To be honest, I don't know how to use PR or the collaboration features on GitHub (as I am not really a programmer, just dabble here and there). How would I do that?

You are also free to take the code to add if you want?

**Comment by abbat** [comment]
OK, I will add your code soon. Thanks!
