### ISSUE TITLE
Token wrong?

### ISSUE THREAD

**Issue by megaxox** [abbat/pclcmd#7]
Invalid 'access_token' provided.

**Comment by abbat** [comment]
Would you provide more info / steps to reproduce?

**Comment by KevinSupertramp** [comment]
Hi. I have the same problem. I generate the token with the command "token" but then I can't get it work when I enter it.

What is the correct command to download a file too, is the source the shared link?

Thanks a lot!

**Comment by abbat** [comment]
@KevinSupertramp, First call

```
$ pclcmd token
```

and open URL in your browser. Now you get `access code`. Paste access code to `token` command:

```
$ pclcmd token <your_access_code>
```

and get `OAuth` token. Paste token in your config file or command line `--token=...`.
